<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
    <None Remove="Images\2946467-200.png" />
    <None Remove="Images\addbaseunit.png" />
    <None Remove="Images\addbutton.png" />
    <None Remove="Images\addbuttonproduct.png" />
    <None Remove="Images\addbuttonsupplier.png" />
    <None Remove="Images\addicon.png" />
    <None Remove="Images\addorder.png" />
    <None Remove="Images\addvariant.png" />
    <None Remove="Images\blacklogo.png" />
    <None Remove="Images\blacktext.png" />
    <None Remove="Images\clipicon.png" />
    <None Remove="Images\close.png" />
    <None Remove="Images\closegray.png" />
    <None Remove="Images\dashboardgreen.png" />
    <None Remove="Images\dashboardgrey.png" />
    <None Remove="Images\dropdown.png" />
    <None Remove="Images\dropup.png" />
    <None Remove="Images\exiticon.png" />
    <None Remove="Images\greenlogo.png" />
    <None Remove="Images\homeicongreen.png" />
    <None Remove="Images\homeicongrey.png" />
    <None Remove="Images\Image1.png" />
    <None Remove="Images\infoicon.png" />
    <None Remove="Images\inventorygreen.png" />
    <None Remove="Images\inventorygrey.png" />
    <None Remove="Images\LOGIN DESIGN.png" />
    <None Remove="Images\loginbg.png" />
    <None Remove="Images\loginslogan.png" />
    <None Remove="Images\logo.png" />
    <None Remove="Images\logouticon.png" />
    <None Remove="Images\minusorder.png" />
    <None Remove="Images\organizationgreen.png" />
    <None Remove="Images\organizationgrey.png" />
    <None Remove="Images\qrcode.png" />
    <None Remove="Images\recordsgreen.png" />
    <None Remove="Images\recordsgrey.png" />
    <None Remove="Images\removeorder.png" />
    <None Remove="Images\schedulegray.png" />
    <None Remove="Images\schedulegreen.png" />
    <None Remove="Images\smartpoultryicon.ico" />
    <None Remove="Images\smartpoultrylogin.png" />
    <None Remove="Images\suppliergreen.png" />
    <None Remove="Images\suppliergrey.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\addbutton.png" />
    <Resource Include="Images\addbuttonproduct.png" />
    <Resource Include="Images\addbuttonsupplier.png" />
    <Resource Include="Images\closegray.png" />
    <Resource Include="Images\schedulegray.png" />
    <Resource Include="Images\schedulegreen.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\smartpoultryicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\2946467-200.png" />
    <Resource Include="Images\addbaseunit.png" />
    <Resource Include="Images\addicon.png" />
    <Resource Include="Images\addorder.png" />
    <Resource Include="Images\addvariant.png" />
    <Resource Include="Images\blacklogo.png" />
    <Resource Include="Images\blacktext.png" />
    <Resource Include="Images\clipicon.png" />
    <Resource Include="Images\close.png" />
    <Resource Include="Images\dashboardgreen.png" />
    <Resource Include="Images\dashboardgrey.png" />
    <Resource Include="Images\dropdown.png" />
    <Resource Include="Images\dropup.png" />
    <Resource Include="Images\exiticon.png" />
    <Resource Include="Images\greenlogo.png" />
    <Resource Include="Images\homeicongreen.png" />
    <Resource Include="Images\homeicongrey.png" />
    <Resource Include="Images\Image1.png" />
    <Resource Include="Images\infoicon.png" />
    <Resource Include="Images\inventorygreen.png" />
    <Resource Include="Images\inventorygrey.png" />
    <Resource Include="Images\LOGIN DESIGN.png" />
    <Resource Include="Images\loginbg.png" />
    <Resource Include="Images\loginslogan.png" />
    <Resource Include="Images\logo.png" />
    <Resource Include="Images\logouticon.png" />
    <Resource Include="Images\minusorder.png" />
    <Resource Include="Images\organizationgreen.png" />
    <Resource Include="Images\organizationgrey.png" />
    <Resource Include="Images\qrcode.png" />
    <Resource Include="Images\recordsgreen.png" />
    <Resource Include="Images\recordsgrey.png" />
    <Resource Include="Images\removeorder.png" />
    <Resource Include="Images\smartpoultrylogin.png" />
    <Resource Include="Images\suppliergreen.png" />
    <Resource Include="Images\suppliergrey.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
