<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="addicon.png" />
    <None Remove="Images\addbaseunit.png" />
    <None Remove="Images\addvariant.png" />
    <None Remove="Images\clipicon.png" />
    <None Remove="Images\dashboardgreen.png" />
    <None Remove="Images\dashboardgrey.png" />
    <None Remove="Images\homeicongreen.png" />
    <None Remove="Images\homeicongrey.png" />
    <None Remove="Images\inventorygreen.png" />
    <None Remove="Images\inventorygrey.png" />
    <None Remove="Images\logo.png" />
    <None Remove="Images\recordsgreen.png" />
    <None Remove="Images\recordsgrey.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="addicon.png" />
    <Resource Include="Images\addbaseunit.png" />
    <Resource Include="Images\addvariant.png" />
    <Resource Include="Images\clipicon.png" />
    <Resource Include="Images\dashboardgreen.png" />
    <Resource Include="Images\dashboardgrey.png" />
    <Resource Include="Images\homeicongreen.png" />
    <Resource Include="Images\homeicongrey.png" />
    <Resource Include="Images\inventorygreen.png" />
    <Resource Include="Images\inventorygrey.png" />
    <Resource Include="Images\logo.png" />
    <Resource Include="Images\recordsgreen.png" />
    <Resource Include="Images\recordsgrey.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Product_Images\" />
  </ItemGroup>

</Project>
